[tool.setuptools.packages.find]
include = ["laueimproc"]

[project]
name = "laueimproc"
dynamic = ["version"]
requires-python = ">=3.9"
dependencies = [
  "fabio",
  "opencv-contrib-python-headless",
  "torch",
]
authors = [
  {name = "Robin RICHARD (robinechuca)", email = "serveurpython.oz@hmail.com"},
]
maintainers = [
  {name = "Robin RICHARD (robinechuca)", email = "serveurpython.oz@hmail.com"},
]
readme = "README.rst"
license = {file = "LICENSE"}
keywords = [
  "laue",
  "multigrain",
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: GPU",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Natural Language :: French",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Image Processing",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Scientific/Engineering :: Physics",
]

[project.optional-dependencies]
gui = [
  "matplotlib",
]
optional = [
  "matplotlib",
  "sphinx",
  "sphinx-rtd-theme",
]

[project.urls]
Repository = "https://framagit.org/robinechuca/laueimproc/"

[tool.setuptools.dynamic]
version = {attr = "laueimproc.__version__"}
